- src/main/java/vazkii/psi/common/block/base/ModBlocks.java
"blockPsiDust"
"blockPsiMetal"
"blockPsiGem"
> Register base decorative block itemstacks in OreDict

- src/main/java/vazkii/psi/common/crafting/recipe/ColorizerChangeRecipe.java
- src/main/java/vazkii/psi/common/item/component/ItemCADColorizer.java
> Add a colorizer swapping recipe.

- src/main/java/vazkii/psi/client/gui/GuiProgrammer.java
- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java
- src/main/java/vazkii/psi/common/spell/trick/entity/PieceTrickSmeltItem.java
Closes #120, #121, and #123
Commits are deliberately separate because each one fixes a separate bug.
> Fix minor bugs

- src/main/java/vazkii/psi/api/spell/ISpellSettable.java
- src/main/java/vazkii/psi/common/block/BlockProgrammer.java
- src/main/java/vazkii/psi/common/item/ItemCAD.java
- src/main/java/vazkii/psi/common/item/ItemSpellBullet.java
- src/main/java/vazkii/psi/common/item/tool/IPsimetalTool.java
This is required for an addon feature.
> Add EntityPlayer to ISpellSettable's function

- src/main/resources/assets/psi/lang/en_US.lang
- src/main/resources/assets/psi/sounds.json
Closes #164 even though it’s already closed
> Add subtitles

- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
Fix ConcurrentModificationException some times crashes minecraft and optimize cleanup method
> Fix ConcurrentModificationException, Optimize

- src/main/java/vazkii/psi/common/lib/LibResources.java
> Use the correct filename for the conjured light texture.

- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
simple fix to #447 
just needed to make sure cameraEntity wasn't null 
(PS: This is my first PR if I did anything wrong please tell me)
> add null check to cameraEntity

- src/main/java/vazkii/psi/api/PsiAPI.java
- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
> CAD will only update their time when they're in the player's hotbar/offhand

- Jenkinsfile
- build.gradle
Basically the same thing as Vazkii/Patchouli@7c54c6ec360211293d84e2ef4846a8d250101f9, will need Jared to set it up on his side though.
@jaredlll08 please check if it's all correct?
> An attempt at maven

- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
- src/main/resources/assets/psi/lang/de_DE.lang
- src/main/resources/assets/psi/lang/en_US.lang
- src/main/resources/assets/psi/lang/fr_FR.lang
- src/main/resources/assets/psi/lang/ja_JP.lang
- src/main/resources/assets/psi/lang/pt_BR.lang
- src/main/resources/assets/psi/lang/zh_CN.lang
- src/main/resources/assets/psi/lang/zh_TW.lang
> Remove outdated energy gain cap message, fixes #505

- src/main/java/vazkii/psi/common/crafting/ModCraftingRecipes.java
- src/main/java/vazkii/psi/common/crafting/recipe/AssemblyScavengeRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/BulletToDriveRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/ColorizerChangeRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/DriveDuplicateRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/SensorAttachRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/SensorRemoveRecipe.java
- src/main/java/vazkii/psi/common/item/ItemCAD.java
- src/main/java/vazkii/psi/common/item/ItemExosuitSensor.java
- src/main/java/vazkii/psi/common/item/ItemSpellDrive.java
- src/main/java/vazkii/psi/common/item/component/ItemCADColorizer.java
- src/main/java/vazkii/psi/data/RecipeGenerator.java
I also started on trying to do the JEI stuff, but it's a bit annoying to do.
Do the data gens yourself, I would've done them if you pushed your changes.
> Convert custom recipe types to use serializers

- src/main/java/vazkii/psi/client/patchouli/PatchouliUtils.java
- src/main/java/vazkii/psi/client/patchouli/SpellGridComponent.java
- src/main/java/vazkii/psi/client/patchouli/SpellPieceComponent.java
- src/main/resources/data/psi/patchouli_books/taurus_silver_handbook/en_us/templates/spell_grid.json
- src/main/resources/data/psi/patchouli_books/taurus_silver_handbook/en_us/templates/spellpiece_spotlight.json
Also readds the mistakenly removed spell piece spotlight template.
> Add spell grid patchouli component and a WIP template using it

- src/main/java/vazkii/psi/api/spell/SpellContext.java
- src/main/java/vazkii/psi/common/item/ItemCAD.java
- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java
- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakInSequence.java
- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickCollapseBlock.java
- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlock.java
PRs included: #540 and #569
[Testing Video](https://www.youtube.com/watch?v=89MAwhd0Bqk)
> Port Harvest Tool Fixes to 1.15

- src/main/java/vazkii/psi/common/item/ItemSpellBullet.java
Closes #582. 
When you forget about your own javadoc comment... and I thought I tested circle bullets, but I only looked at the pretty circle they make...
> Fix entity creating bullets not casting

- src/generated/resources/data/psi/recipes/cad_assembly_psimetal.json
- src/generated/resources/data/psi/recipes/gold_to_psimetal_assembly_upgrade.json
- src/main/java/vazkii/psi/client/core/handler/ContributorSpellCircleHandler.java
- src/main/java/vazkii/psi/data/TrickRecipeGenerator.java
> Fix psimetal assembly recipes

- build.gradle
- src/generated/resources/data/psi/recipes/spell_bullet_charge_upgrade.json
- src/generated/resources/data/psi/recipes/spell_bullet_circle_upgrade.json
- src/generated/resources/data/psi/recipes/spell_bullet_grenade_upgrade.json
- src/generated/resources/data/psi/recipes/spell_bullet_loopcast_upgrade.json
- src/generated/resources/data/psi/recipes/spell_bullet_mine_upgrade.json
- src/generated/resources/data/psi/recipes/spell_bullet_projectile_upgrade.json
- src/main/java/vazkii/psi/client/gui/GuiProgrammer.java
- src/main/java/vazkii/psi/client/jei/JEICompat.java
- src/main/java/vazkii/psi/client/jei/crafting/BulletToDriveExtension.java
- src/main/java/vazkii/psi/client/jei/crafting/DriveDuplicateExtension.java
- src/main/java/vazkii/psi/client/jei/crafting/package-info.java
- src/main/java/vazkii/psi/common/core/handler/ConfigHandler.java
- src/main/java/vazkii/psi/common/crafting/ModCraftingRecipes.java
- src/main/java/vazkii/psi/common/crafting/recipe/BulletToDriveRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/BulletUpgradeRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/DriveDuplicateRecipe.java
- src/main/java/vazkii/psi/common/crafting/recipe/SensorRemoveRecipe.java
- src/main/java/vazkii/psi/common/item/ItemSpellBullet.java
- src/main/java/vazkii/psi/common/item/ItemSpellDrive.java
- src/main/java/vazkii/psi/common/item/armor/ItemPsimetalExosuitHelmet.java
- src/main/java/vazkii/psi/data/RecipeGenerator.java
- src/main/java/vazkii/psi/data/WrapperResult.java
- src/main/resources/assets/psi/lang/en_us.json
- src/main/resources/en_us_base.json
Read the commit messages as always :P
> Bullet cloning, mostly

- src/main/java/vazkii/psi/api/PsiAPI.java
- src/main/java/vazkii/psi/api/material/PsimetalToolMaterial.java
- src/main/java/vazkii/psi/common/item/ItemCAD.java
- src/main/java/vazkii/psi/common/item/armor/ItemPsimetalArmor.java
- src/main/java/vazkii/psi/common/item/tool/IPsimetalTool.java
- src/main/java/vazkii/psi/common/item/tool/ItemPsimetalAxe.java
- src/main/java/vazkii/psi/common/item/tool/ItemPsimetalPickaxe.java
- src/main/java/vazkii/psi/common/item/tool/ItemPsimetalShovel.java
- src/main/java/vazkii/psi/common/item/tool/ItemPsimetalSword.java
*insert some insightful explanation that Kame will not read anyways*
> More fixes

- src/main/java/vazkii/psi/common/item/ItemCAD.java
- src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickEbonyIvory.java
- src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickGreaterInfusion.java
- src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickInfusion.java
PsiAPI.registerTrickRecipe() only works for JEI, and the real recipe never changes before.
Happy New Year!
> FIX PsiAPI.registerTrickRecipe() only works for JEI

- src/main/java/vazkii/psi/client/gui/GuiProgrammer.java
Because sometimes people have errors on import and ask for help.
Also I couldn't look at the mix of getMinecraft() and Minecraft.getInstance().
> Log exceptions that happen on spell clipboard import

- src/main/java/vazkii/psi/client/gui/GuiProgrammer.java
> fix game crash when closeComment

- src/main/java/vazkii/psi/api/cad/ISocketable.java
- src/main/java/vazkii/psi/common/block/tile/container/ContainerCADAssembler.java
> fix game crash when place something isn't bullet in the ISocketable items

- src/main/java/vazkii/psi/api/spell/SpellRuntimeException.java
- src/main/java/vazkii/psi/common/spell/operator/number/PieceOperatorGammaFunc.java
Fixes operator: gamma function throwing an unhandled exception when its input is zero, crashing the game.
> Fix operator: gamma function crashing when input is zero

- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
> Stop spectators from loopcasting

- src/main/java/vazkii/psi/api/spell/IErrorCatcher.java
- src/main/java/vazkii/psi/common/spell/SpellCompiler.java
> Fix error catcher evaluation order

- src/main/java/vazkii/psi/api/spell/SpellMetadata.java
- src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java
- src/main/java/vazkii/psi/common/item/ItemCAD.java
Cleaning up parts I meant to do in the last API update
> Additional API fixes 

- src/main/java/vazkii/psi/common/entity/ModEntities.java
> Make spell circles fire immune

- Jenkinsfile
Look there was a build on 1.12 last month, so it gets future proofed
> Future proof Jenkinsfile

- src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickTill.java
> Fixed Trick: Till not working (#775)

- src/main/java/vazkii/psi/common/item/tool/ToolSocketable.java
Simple fix for radial menu crash on tools and armor.
> fix #833 and #834
