src/main/java/vazkii/psi/common/block/base/BlockMod.java
Fixes a crash when accessing the block with reflection.
Specifically: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49
=> Add missing @SideOnly(Side.CLIENT) to getCustomMeshDefinition

src/main/java/vazkii/psi/common/entity/EntitySpellGrenade.java
The timeAlive field was never getting updated and was always 0. The ticksExisted field already exists and does the same job, so switched to that.
=> Made grenade correctly track its lifetime. Fixes #219

src/main/java/vazkii/psi/common/spell/selector/entity/PieceSelectorNearbySmeltables.java
Makes Nearby Smeltables actually select only smeltables.
=> Fix Selector Nearby Smeltables

src/main/java/vazkii/psi/common/spell/operator/number/PieceOperatorMax.java
d3 defaults to Double.MIN_VALUE, which is the smallest POSITIVE number a double can hold. This means if d1 or d2 are a negative number, it will always return Double.MIN_VALUE instead of ignoring d3 like you'd expect. Using Double.NEGATIVE_INFINITY instead will resolve this.
=> Logic error using negative numbers in Max operator

src/main/java/vazkii/psi/common/block/BlockConjured.java
This fixes #91 and its duplicate #285. It turned out to be really simple to implement thanks to @williewillus's pointer to `Block.getBoundingBox` (in #91).
~There's some duplication now, which I unfortunately couldn't come up with a way around, but I suppose it's not bad.~
=> Conjured Light Bounding Box Fix

src/main/java/vazkii/psi/common/entity/EntitySpellProjectile.java
Spells do not have SpellContexts (in at least some cases) for clients other than the spell owner. This can cause a NPE in the projectile's collision handling code, which blindly assumes the context is there to set a value on it. This change simply adds a null check to the relevant callback.
=> Added a null check to projectile collision callback. Fixes #376

src/main/java/vazkii/psi/common/item/tool/ItemPsimetalTool.java
Instead of checking for a hardcoded value for reach use forge's reach attribute thus fixing #450
=> Use forge reach attribute instead of hardcoded reach

src/main/java/vazkii/psi/common/block/BlockPsiDecorative.java, src/main/java/vazkii/psi/common/spell/operator/entity/PieceOperatorEntityMotion.java, src/main/resources/assets/psi/lang/en_US.lang
Adds all the decorative blocks back to creative tabs
Fixes the lang typo
Fixes entity motion displaying wrong magnitude for the player
~~Only thing I'm unsure about is https://github.com/Kamefrede/Psi/blob/18130ac16aefd1f08ea6dba576d461a57e75a50b/src/main/java/vazkii/psi/common/spell/operator/entity/PieceOperatorEntityMotion.java#L52 , if it should remain 10 or be changed to 33,4 ( 10 multiplied by the add motion multiplier)~~
=> Adds decorative block back to creative tab, fixes lang typo, fixes player motion displaying incorrect value

build.gradle, src/main/java/vazkii/psi/common/crafting/ModCraftingRecipes.java, src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickEbonyIvory.java, src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickGreaterInfusion.java, src/main/java/vazkii/psi/common/spell/trick/infusion/PieceTrickInfusion.java
Gradle stuff taken from Vazkii/Patchouli#2, and my port of it to Botania. Deobf jars are passe, but if you want, feel free to put that back in. 
Moves trick recipe registration to crafting recipes because it turns out class literals don't classload reliably and it would only happen once you opened the spellpiece selection in the programmer, requiring a resource reload to put them in JEI.
=> Port gradle fixes, fix JEI trick crafting not being shown

src/main/java/vazkii/psi/api/spell/SpellContext.java, src/main/java/vazkii/psi/client/render/entity/RenderSpellCircle.java, src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java, src/main/java/vazkii/psi/common/entity/EntitySpellCircle.java, src/main/java/vazkii/psi/common/entity/EntitySpellProjectile.java, src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/item/ItemSpellBullet.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickCollapseBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlock.java
Addresses some of the problems described in #537 
Namely, the CAD being able to harvest blocks that ordinarily require special tools (like Forestry Hives)
Also when a spell is cast, the CAD stack is part of the context, also is saved in projectile and spell circle so it is more likely to be available for the break block spell.
I'm not really happy with the current PR / implementation though so looking for comments and discussion about how it could be changed.
- Have the CAD stack used to cast a spell available in the spell context
- Makes sure that the CAD acts only as a pickxe, axe and shovel
- Makes sure that the CAD or psimetal tool that casted the spell is used to check harvestability (not the main hand). Before this change it only checked harvest level.
- Makes sure that we use …
=> Fix break tool and level

src/main/java/vazkii/psi/client/fx/ParticleRenderDispatcher.java
Using glPopAttrib and glPushAttrib can cause GLStateManager to become out of sync with the real OpenGL state. This means that GLStateManager will not update the real OpenGL state correctly which can cause graphical glitches in other mods. See Electroblob77/Wizardry#170.
Should fix Vazkii/Psi#525
=> Use GLStateManager over glPopAttrib / glPushAttrib

src/main/java/vazkii/psi/client/patchouli/SpellPieceComponent.java, src/main/resources/data/psi/patchouli_books/taurus_silver_handbook/en_us/categories/basics.json, src/main/resources/data/psi/patchouli_books/taurus_silver_handbook/en_us/entries/spotlight_test.json, src/main/resources/data/psi/patchouli_books/taurus_silver_handbook/en_us/templates/spellpiece_spotlight.json
* Spell piece component, takes x/y positions and piece registry name.
* Spell piece spotlight template, basically a copy of the Patchouli item spotlight but done as a template.
* Example page for usage of the spotlight template. It is kept as a debug entry so it doesn't show up in actual builds of the mod.
=> Add Patchouli spell piece component, spotlight page, and an example page

src/main/java/vazkii/psi/api/spell/SpellContext.java, src/main/java/vazkii/psi/client/render/entity/RenderSpellCircle.java, src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java, src/main/java/vazkii/psi/common/entity/EntitySpellCircle.java, src/main/java/vazkii/psi/common/entity/EntitySpellProjectile.java, src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/item/ItemSpellBullet.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakInSequence.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickCollapseBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlock.java
Partially reverts https://github.com/Vazkii/Psi/pull/540 (commit https://github.com/Vazkii/Psi/pull/540/commits/bd3c6be639f9f2d1b65b6d43af03e7c13334c11a) as it is a copy of the CAD and some spells require the actual CAD like Save Vector.
Adds a method in SpellContext that gets the tool that is used for harvesting. This fixes the previous PR not working with Psi Metal Armour. Now it uses the CAD if the Psi Metal Tool in the context does not have any tool classes.
Switched to using setHarvestLevel for ItemCAD so no longer need to override a bunch of methods. One downside to this is that a restart is required to reflect config changes.
Fixed experience orbs not dropping from broken blocks. (was missing some code that is usually called in `PlayerInteractionManager#tryHarvestBlock`).
Fixed a …
=> Fix harvesting tool

src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java
The CAD was not able to break certain blocks that had a material assigned that required a tool to break, but did not return an associated tool class.
The vanilla pickaxe can break any `Material.ROCK`, `Material.IRON` or `Material.ANVIL` if the block does not have a matching harvest tool.
The CAD is updated to do the same as that in this PR.
Also updates `canHarvestBlock` as discussed on discord to match MinecraftForge/MinecraftForge#6632
=> Fix CAD harvesting for pickaxe materials on blocks with no harvest tool

src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java
This makes the CAD only act as a tool while a harvest check is ongoing.
It also sets the main hand to the tool stack and then resets the main hand back to the previous stack after the check is done (so that we can just use `block.canHarvestBlock(world, pos, player)` and have better compatiblity). Ideally this would be swapping the stacks but then we'd need to pass the slot the tool is in rather than just the tool stack in that case.
The createBreakEvent could possibly use a similar change since right now listeners to the event don't have access to the actual stack doing the harvesting. But this is quite the rabbit hole since mods may modify the main hand during that event...
Still need to take a look at maybe switching to using NBT instead of using global state as well. Was thinking this …
=> Make CAD only act as a tool during harvest check

src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickCollapseBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickCollapseBlockSequence.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlock.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlockSequence.java, src/main/java/vazkii/psi/common/spell/trick/entity/PieceTrickAddMotion.java
Ports https://github.com/Vazkii/Psi/pull/586 to 1.15
Also includes a commit that switches from using Block to BlockState (since that seems to be the correct way to do it in 1.15, and fixes createBreakEvent to use our canHarvestBlock (experience now properly drops from blocks)
=> Port 'Make CAD only act as a tool during harvest check' to 1.15

src/main/java/vazkii/psi/common/Psi.java, src/main/java/vazkii/psi/common/item/ItemCAD.java
Ports https://github.com/Vazkii/Psi/pull/592 to 1.15
Also moves the config registration to the mod constructor (see `net.minecraftforge.common.ForgeMod`).
This PR fixes https://github.com/Vazkii/Psi/issues/591
[Video](https://www.youtube.com/watch?v=G0orh3Lw1ks)
=> Port 'Fix CAD harvest level not updating with config' and Fix config registration

src/main/java/vazkii/psi/common/item/ItemCAD.java
This PR has the cad harvest level update properly while in-game again (a previous PR of mine broke this feature by changing it to setting the harvest level in the constructor, which, in 1.15.2, the config is not loaded at that point).
[Video](https://www.youtube.com/watch?v=gcBohEG_rxE)
This PR will also fix https://github.com/Vazkii/Psi/issues/591 once it is ported to 1.15.2. But that might need some more changes.
=> Fix CAD harvest level not updating with config

src/main/java/vazkii/psi/client/core/handler/ColorHandler.java, src/main/java/vazkii/psi/common/item/armor/ItemPsimetalArmor.java, src/main/java/vazkii/psi/common/item/armor/ItemPsimetalExosuitHelmet.java
Currently, attaching sensors does not change the color of either the item or the model. The default color is also not present.
This PR addresses the three points needed to fix this:
1) Replace the mistaken double call to boots with the helmet when registering `ColorHandler` so that the helmet item colorizes the sensor correctly
2) Implement `IDyeableArmorItem` on `ItemPsimetalExosuitHelmet` so that the sensor's model gets rendered alongside the regular model
3) Reverse the logic in `ItemPsimetalArmor#getArmorTexture` so that the sensor's model gets colorized, because the "overlay" type actually represents the uncolored layer
=> Fix lack of sensor colors

build.gradle, src/main/java/vazkii/psi/common/block/BlockConjured.java, src/main/java/vazkii/psi/common/block/base/ModBlocks.java
Conjured blocks were suffocating entities and did not allow the third person camera to pass through them.
This PR fixes the above referencing Vanilla Glass and Botania's [Mana Glass](https://github.com/Vazkii/Botania/blob/7112f0291337ea66b769b1c40194557b28b56af5/src/main/java/vazkii/botania/common/block/ModBlocks.java#L247).
Also switched to using the official Sponge maven (for MixinGradle) since the creeper host one died. (Let me know if that commit is not desired and I will remove it.)
<details>
<summary>Screenshots</summary>
**After**
**Before**
</details>
=> Fix conjured blocks

src/main/java/vazkii/psi/common/spell/SpellCompiler.java
Error handlers could be called before their parameters are evaluated, resulting in null values.
It was also possible to use a fallback value that depends on the target of the error handler, resulting in null values or NullPointerExceptions.
This PR fixes these problems by ensuring that params of error handlers are always evaluated before the target of the handler and by treating error handler params that depend on the target of the handler as a circular dependency.
=> Fix error handler param evaluation order, prevent self dependency

src/main/java/vazkii/psi/common/core/handler/PlayerDataHandler.java, src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickRussianRoulette.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickSpinChamber.java
Trick: spin chamber would error saying that it can only be used in a CAD when used with loopcast. This PR fixes that and prevents the CAD from playing the reequip animation when the trick changes the selected slot.
=> Fix trick: spin chamber not working with loopcast

src/main/java/vazkii/psi/api/spell/SpellContext.java
Makes slot shift relative to active hotbar slot when CAD is in offhand.
=> Fix shift target slot not working when CAD is in offhand

src/main/java/vazkii/psi/api/cad/ISocketable.java, src/main/java/vazkii/psi/client/gui/GuiSocketSelect.java, src/main/java/vazkii/psi/common/core/handler/capability/SocketWheel.java, src/main/java/vazkii/psi/common/item/tool/ToolSocketable.java
Allows addons to use more than 12 slots and display their custom icons in the socket selector GUI.
=> Give addons more control over socket selector GUI

src/main/java/vazkii/psi/api/cad/EnumCADStat.java, src/main/java/vazkii/psi/common/item/ItemCAD.java, src/main/java/vazkii/psi/common/item/component/DefaultStats.java, src/main/resources/assets/psi/lang/en_us.json, src/main/resources/en_us_base.json
The number of saved vectors available should be independent from the number of sockets available. This would allow addons to add sockets with independent saved vector and socket count. For sockets added by Psi the saved vector count is the same as before with saved vector count added to their tooltip.
=> Separate saved vector count from socket count

src/main/java/vazkii/psi/common/spell/constant/PieceConstantNumber.java
Number Constants had to be re-added when switching their signs. This PR allows the sign of the constant to be switched to positive with '+' and to negative with '-' without having to delete its value.
=> Add shortcut to switch Number Constant back to positive

src/main/java/vazkii/psi/client/gui/GuiProgrammer.java
Makes adding connectors with keyboard controls easier by adding shift + arrow keys as a shortcut to create a connector connecting to the selected piece.
=> Create connector keyboard shortcut in programmer

src/main/java/vazkii/psi/api/spell/SpellPiece.java, src/main/java/vazkii/psi/common/spell/other/PieceConnector.java, src/main/java/vazkii/psi/common/spell/other/PieceCrossConnector.java
It would allow displaying connectors properly with pieces that have "output parameters" like the cross connector or have connections that don't have a parameter associated like my clockwise connector.
=> Add API for checking piece input sides

src/main/java/vazkii/psi/api/spell/SpellParam.java, src/main/java/vazkii/psi/api/spell/SpellPiece.java, src/main/java/vazkii/psi/api/spell/param/ParamAny.java, src/main/java/vazkii/psi/common/spell/other/PieceCrossConnector.java
Makes it easier to see which parameter is on the same side as another one and where, also useful for rendering something like my circle connector properly.
Arrow type API removes the need to reimplement parameter drawing for every piece which doesn't draw an arrow for one of its parameters, like cross connector.
=> Draw overlapping params properly, arrow type API

src/main/java/vazkii/psi/common/spell/trick/PieceTrickBreakLoop.java
Trick: Break Loop shouldn't imply a Trick: Die. This would allow for more advanced uses of the piece, making it more than something with barely any real use cases.
=> Trick: Break Loop shouldn't stop the current cast

src/main/java/vazkii/psi/api/spell/SpellHelpers.java, src/main/java/vazkii/psi/common/spell/operator/block/PieceOperatorBlockComparatorStrength.java, src/main/java/vazkii/psi/common/spell/operator/block/PieceOperatorBlockHardness.java, src/main/java/vazkii/psi/common/spell/operator/block/PieceOperatorBlockLightLevel.java, src/main/java/vazkii/psi/common/spell/operator/block/PieceOperatorBlockMiningLevel.java, src/main/java/vazkii/psi/common/spell/operator/block/PieceOperatorBlockSideSolidity.java, src/main/java/vazkii/psi/common/spell/operator/entity/PieceOperatorClosestToLine.java, src/main/java/vazkii/psi/common/spell/operator/entity/PieceOperatorEntityRaycast.java, src/main/java/vazkii/psi/common/spell/operator/vector/PieceOperatorVectorAbsolute.java, src/main/java/vazkii/psi/common/spell/operator/vector/PieceOperatorVectorRaycast.java, src/main/java/vazkii/psi/common/spell/operator/vector/PieceOperatorVectorRaycastAxis.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickChangeSlot.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickDetonate.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickOvergrow.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickParticleTrail.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickPlaySound.java, src/main/java/vazkii/psi/common/spell/trick/PieceTrickTorrent.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickMoveBlockSequence.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickTill.java, src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickTillSequence.java
Most addons have to reimplement SpellHelpers without this change.
=> Move SpellHelpers to API

src/main/java/vazkii/psi/client/gui/widget/PiecePanelWidget.java
The panel cursor would always select a piece position from the first page, even if a later page was selected. This would cause its position not to update when opening the panel again in a different position while not on the first page.
Bug reported by TauKinth
=> Fixed Panel Cursor Issue

src/main/resources/data/psi/advancements/main/ebony_assembly_pickup.json, src/main/resources/data/psi/advancements/main/ebony_pickup.json, src/main/resources/data/psi/advancements/main/encyclopaedia_psionica.json, src/main/resources/data/psi/advancements/main/gold_assembly_pickup.json, src/main/resources/data/psi/advancements/main/iron_cad_pickup.json, src/main/resources/data/psi/advancements/main/ivory_assembly_pickup.json, src/main/resources/data/psi/advancements/main/ivory_pickup.json, src/main/resources/data/psi/advancements/main/psidust.json, src/main/resources/data/psi/advancements/main/psigem_pickup.json, src/main/resources/data/psi/advancements/main/psimetal_assembly_pickup.json, src/main/resources/data/psi/advancements/main/psimetal_pickup.json, src/main/resources/data/psi/advancements/main/root.json
Minecraft version: **1.19.2**
Because of an invalid advancement format, all main advancements were unlocked on inventory change.
```diff
"conditions": {
"items": [
{
-     "item": "minecraft:example_item"
+     "items": ["minecraft:example_item"]
}
]
}
```
In recent versions, the format has changed. The field has been renamed from `item` to `items` and now accepts list of item ids instead of a single item id.
=> fix: All main advancements unlocking instantly for 1.19.2

src/main/resources/data/psi/advancements/main/ebony_assembly_pickup.json, src/main/resources/data/psi/advancements/main/ebony_pickup.json, src/main/resources/data/psi/advancements/main/encyclopaedia_psionica.json, src/main/resources/data/psi/advancements/main/gold_assembly_pickup.json, src/main/resources/data/psi/advancements/main/iron_cad_pickup.json, src/main/resources/data/psi/advancements/main/ivory_assembly_pickup.json, src/main/resources/data/psi/advancements/main/ivory_pickup.json, src/main/resources/data/psi/advancements/main/psidust.json, src/main/resources/data/psi/advancements/main/psigem_pickup.json, src/main/resources/data/psi/advancements/main/psimetal_assembly_pickup.json, src/main/resources/data/psi/advancements/main/psimetal_pickup.json, src/main/resources/data/psi/advancements/main/root.json
Fixes #790 
Minecraft version: **1.18**
Because of an invalid advancement format, all main advancements were unlocked on inventory change.
```diff
"conditions": {
"items": [
{
-     "item": "minecraft:example_item"
+     "items": ["minecraft:example_item"]
}
]
}
```
In recent versions, the format has changed. The field has been renamed from `item` to `items` and now accepts list of item ids instead of a single item id.
=> fix: All main advancements unlocking instantly for 1.18
